gjtorikian/commonmarker

README.md
Rakefile
bin/commonmarker
commonmarker.gemspec
ext/commonmarker/commonmarker.c
ext/commonmarker/extconf.rb
lib/commonmarker.rb
lib/commonmarker/renderer/html_renderer.rb
script/update_submodules
test/spec_tests.json
test/test_basics.rb
test/test_helper.rb
test/test_maliciousness.rb
test/test_spec.rb

Closes https://github.com/gjtorikian/commonmarker/issues/2.

Better memory management

---

Gemfile
LICENSE.txt
README.md
commonmarker.gemspec
ext/commonmarker/commonmarker.c
lib/commonmarker.rb
lib/commonmarker/config.rb
script/cibuild
script/update_submodules
test/benchmark.rb
test/spec_tests.json
test/test_basics.rb
test/test_doc.rb
test/test_gc.rb
test/test_helper.rb
test/test_linebreaks.rb
test/test_maliciousness.rb
test/test_pathological_inputs.rb
test/test_smartpunct.rb
test/test_spec.rb

This implements more of the tests in the libcmark suite. Closes https://github.com/gjtorikian/commonmarker/issues/6.

More testing

---

ext/commonmarker/commonmarker.c
test/fixtures/dingus.md
test/test_attributes.rb

Closes https://github.com/gjtorikian/commonmarker/issues/15.

Add `sourcepos` information

---

ext/commonmarker/commonmarker.c
ext/commonmarker/commonmarker.h
test/test_encoding.rb

Also, close https://github.com/gjtorikian/commonmarker/issues/30.

Update cmark to 0.27.1

---

README.md

Closes https://github.com/gjtorikian/commonmarker/issues/52

Document the extensions in the README

---

README.md

Addendum to #52.
/cc @gjtorikian @safinaskar

Link to libcmark-gfm

---

lib/commonmarker/renderer/html_renderer.rb
test/test_renderer.rb

Closes https://github.com/gjtorikian/commonmarker/issues/56.

Reset `needs_close_tbody` when entering tables

---

README.md
ext/commonmarker/cmark.h
ext/commonmarker/table.c
lib/commonmarker/config.rb
test/test_extensions.rb

https://github.com/github/cmark/pull/86
https://github.com/github/cmark/pull/87

Support the TABLE_PREFER_STYLE_ATTRIBUTES render option

---

.travis.yml
README.md
lib/commonmarker/config.rb

Closes https://github.com/gjtorikian/commonmarker/issues/85.

Allow `:UNSAFE` option for parsing

---

lib/commonmarker/config.rb

Should close https://github.com/gjtorikian/commonmarker/issues/96

Indicte the context of an option

---

.github/workflows/lint.yml

CI: Drop a duplicate 'bundle install'

---

.github/workflows/cruby-build-and-install.yml
.github/workflows/generic-build-and-install.yml
.github/workflows/lint.yml
.github/workflows/test.yml
ext/commonmarker/src/comrak_options.rs
ext/commonmarker/src/lib.rs

This PR just tightens up some of the workflow actions, fixes a few Clippy errors, and makes a few corrected suggestions @ianks had made over at https://github.com/gjtorikian/commonmarker/pull/194.

Clippy and cleanup

---

.github/workflows/cruby-build-and-install.yml
.github/workflows/generic-build-and-install.yml
Cargo.lock
ext/commonmarker/Cargo.toml
lib/commonmarker/version.rb

Windows build

---

Rakefile

closes https://github.com/gjtorikian/commonmarker/issues/259

Reintroduce `ruby` platform releases

---

.github/workflows/lint.yml
Cargo.toml
ext/commonmarker/Cargo.toml
lib/commonmarker/version.rb

should close https://github.com/gjtorikian/commonmarker/issues/270

Builds on behalf of Ruby 3.3

---

ext/commonmarker/src/node.rs

node: remove duplicate fence info method defs.

---

lib/commonmarker/version.rb

hoping to test https://github.com/gjtorikian/commonmarker/pull/295 with the newer release task [5212ee4](https://github.com/gjtorikian/commonmarker/commit/5212ee4786bc337027bf21c3c5c813e1cc135622)
·

:gem: 1.1.3

---

ext/commonmarker/src/lib.rs
ext/commonmarker/src/node.rs
ext/commonmarker/src/plugins.rs
ext/commonmarker/src/plugins/syntax_highlighting.rs
lib/commonmarker/version.rb
test/node_test.rb

Will close https://github.com/gjtorikian/commonmarker/issues/293.

Support plugins when processing node tree

---

lib/commonmarker/version.rb

xref https://github.com/gjtorikian/commonmarker/issues/358

Address packaging issues with ruby 3.3.x

---

Cargo.lock
test/node_test.rb
test/sourcepos_test.rb

This contains the fix upstream for #376

Bump comrak from 0.39.0 to 0.39.1

---

lib/commonmarker/version.rb

Preparing a release with #377.

Bump gem to 2.3.1.
