gjtorikian/commonmarker

ext/commonmarker/commonmarker.c
lib/commonmarker.rb
lib/commonmarker/renderer/html_renderer.rb
test/test_gc.rb
test/test_maliciousness.rb

Implement Node class in C, fix memory management

---

ext/commonmarker/commonmarker.c
lib/commonmarker.rb
test/fixtures/curly.md
test/test_encoding.rb
test/test_helper.rb

Resolves https://github.com/gjtorikian/commonmarker/issues/9.
This might partly be a result of [Houdini's needs](https://github.com/vmg/houdini/tree/59727b85553b70d468743076219e620d6c0d3cad#houdini---the-escapist):
> Houdini parses only UTF-8 strings, and generates only UTF-8 strings. If you are using another encoding, you should probably transcode before passing the buffer to Houdini.

UTF-8 issues

---

ext/commonmarker/extconf.rb

For whatever reason, OS X's system Ruby is messed up, and can't find the newly built CMark lib. Just skip the check if it's being used.
Closes https://github.com/gjtorikian/commonmarker/issues/13.

Don't perform `find_library` on OS X's system Ruby

---

README.md
lib/commonmarker.rb
lib/commonmarker/node.rb
lib/commonmarker/renderer.rb
test/test_attributes.rb
test/test_node.rb

Closes https://github.com/gjtorikian/commonmarker/issues/23.
@dgraham, how's this work for you? `walk` has been renamed `each` so that all the `Enumerable` methods can function. I only added a test for `select` but can add more if you think there's something to explicitly test.

Make `Node` an `Enumerable`

---

lib/commonmarker/node.rb
lib/commonmarker/node/inspect.rb
test/test_node.rb

Supporting pretty-printing / inspecting is inevitable for debugging.
Resolve #42 
```sh
bundle exec ruby -Ilib -rcommonmarker -e 'pp CommonMarker.render_doc("Hi *there*, I am mostly text!")'
```
Shows:
```
#<CommonMarker::Node(document):
sourcepos={:start_line=>1, :start_column=>1, :end_line=>1, :end_column=>29}
children=[#<CommonMarker::Node(paragraph):
sourcepos={:start_line=>1,
:start_column=>1,
:end_line=>1,
:end_column=>29}
children=[#<CommonMarker::Node(text):
sourcepos={:start_line=>0,
:start_column=>0,
:end_line=>0,
:end_column=>0},
string_content="Hi ">,
#<CommonMarker::Node(emph):
sourcepos={:start_line=>0,
:start_column=>0,
:end_line=>0,
:end_column=>0}
children=[#<CommonMarker::Node(text):
sourcepos={:start_line=>0,
:start_column=>0,
:end_line=>0,
:end_column=>0}, …
```

support p and pp for CommonMarker::Node

---

README.md
ext/commonmarker/commonmarker.c
lib/commonmarker/config.rb
lib/commonmarker/node.rb
lib/commonmarker/version.rb
test/test_node.rb
test/test_plaintext.rb

`cmark-gfm` got plaintext rendering support! We also lost an option, and gained one.

Plaintext renderer support

---

README.md
bin/commonmarker
ext/commonmarker/commonmarker.c
lib/commonmarker/config.rb
lib/commonmarker/renderer.rb
lib/commonmarker/renderer/html_renderer.rb
test/test_spec.rb

There was some incomplete support, this is just rounding it off and enabling it on all the same tests we put the normal renderer through.
Most of it doesn't actually need to be switched on or off specially — we rely on the fact that e.g. we'll only get a `strikethrough` or `table_cell` node if the parser had that enabled in the first place. The only switch we do have which is renderer-specific is `tagfilter`.
/cc @gjtorikian for review

Full support for options and extensions in HtmlRenderer

---

README.md

The link referencing the CMark docs drifted by a few dozen lines, this one updates it to the current one. We could also point it to a specific commit with [this link](https://git.io/v7nhN) if you'd prefer. Could not label this PR, should probably be filed under "huge nitpick", or "documentation drive-thru". Haven't read the rest of the source code yet, when my inner reviewer kicked in. I should probably stop githubbing after work. ANYWAY, yay open source!

Update link to the CMark docs options

---

ext/commonmarker/commonmarker.c
lib/commonmarker/node.rb

When parsing Commonmark, traversing the nodes and then re-generating Commonmark, table rows longer than 120 characters are broken as a result of the hard-coded column wrapping.
This patch introduces an optional rendering parameter to specify the width, so callers can opt for "0" to omit all wrapping when necessary (_or choose a different wrapping column as desired_).

Fix issues with tables during a round-trip parsing CM and then producing CM again.

---

README.md

This pretty simple PR:
1. Adds missing `:STRIKETHROUGH_DOUBLE_TILDE` option to the parse options table.
2. Sorts both the parse and the render options in the tables to make human eyes happy again. :slightly_smiling_face:

Update both parse and render options in README

---

ext/commonmarker/html.c
lib/commonmarker/renderer/html_renderer.rb
test/test_footnotes.rb

The current HTML renderer outputs square brackets around footnotes.
```html
This is a test.<sup class="footnote-ref"><a href="#fn1" id="fnref1">[1]</a></sup>
```
This is not consistent with Kramdown's rendering (see [Babelmark](http://johnmacfarlane.net/babelmark2/?text=This+is+a+test.%5B%5E1%5D%0A%0A%5B%5E1%5D%3A+Of+footnotes.)). I assume that this should be considered a bug given that the purpose of introducing the change was [to allow the Cmark renderer to be used in place of Kramdown](https://github.com/github/cmark/pull/64#issue-151303356). It also just looks weird.
Since the bug is in the Cmark project perhaps it would be best to suggest the fix there? Sorry, this is the first time I've tried to do something like this so I'm not sure. I came across the issue when using CommonMarker …

Remove square brackets when rendering HTML for footnotes

---

ext/commonmarker/cmark-gfm_version.h
ext/commonmarker/table.c

Includes a fix which causes footnote references being rendered inside table cells.
/cc @gjtorikian @digitalmoksha

bump to cmark-gfm 0.28.3.gfm.16

---

.gitmodules
README.md
ext/commonmarker/cmark-gfm-core-extensions.h
ext/commonmarker/cmark-gfm-extension_api.h
ext/commonmarker/cmark-gfm.h
ext/commonmarker/cmark-gfm_version.h
ext/commonmarker/commonmark.c
ext/commonmarker/html.c
ext/commonmarker/inlines.c
ext/commonmarker/node.c
ext/commonmarker/strikethrough.c
ext/commonmarker/syntax_extension.c
ext/commonmarker/syntax_extension.h
ext/commonmarker/table.c
ext/commonmarker/xml.c
lib/commonmarker/config.rb
lib/commonmarker/renderer/html_renderer.rb
test/test_extensions.rb
test/test_spec.rb

Pulls in https://github.com/github/cmark-gfm/pull/123, defaulting to safe operation.
/cc @gjtorikian for your consideration. This change requires downstream users to use `:UNSAFE` to get the effect that `:DEFAULT` previously would.
Alternatively, we could insulate users of commonmarker from the cmark-gfm change by sending `CMARK_OPT_UNSAFE` to the library _unless_ `:SAFE` was provided -- it depends on how much we'd be concerned about users updating and complaining, I think, but I do believe defaulting to non-XSSable output is the better option.

Latest upstream

---

README.md

I just noticed a couple whitespace issues in the README when looking over the transition from 0.18.1 to 0.18.2, and #87 had inadvertently added a couple of inconsistencies.

Fixes up whitespace problems introduced in #87

---

ext/commonmarker/blocks.c
ext/commonmarker/buffer.c
ext/commonmarker/chunk.h
ext/commonmarker/cmark-gfm.h
ext/commonmarker/cmark-gfm_version.h
ext/commonmarker/commonmark.c
ext/commonmarker/html.c
ext/commonmarker/inlines.c
ext/commonmarker/iterator.h
ext/commonmarker/map.h
ext/commonmarker/node.h
ext/commonmarker/parser.h
ext/commonmarker/render.c
ext/commonmarker/render.h
ext/commonmarker/scanners.c
ext/commonmarker/scanners.h

cmark 0.29.0 has been released (as has the same version of the spec, though the spec website hasn't updated yet) -- I've published cmark-gfm 0.29.0.gfm.0 just now which just pulls in changes made since then, and here's the commonmarker change.
(Maybe worth noting: cmark-gfm's change to safe-by-default/unsafe-via-option was taken up in upstream cmark!)

update to cmark-gfm 0.29.0.gfm.0

---

ext/commonmarker/tasklist.c
lib/commonmarker/renderer.rb
lib/commonmarker/renderer/html_renderer.rb
test/test_tasklists.rb

`tasklist_state` is inverted; fix this from upstream. See https://github.com/github/cmark-gfm/pull/142.

tasklist state inverted

---

README.md

`:tasklist` extension has been implemented but undocumented yet.
This PR adds its short description to README.

Add tasklist extension description to README

---

bin/commonmarker
test/fixtures/strong.md
test/fixtures/table.md
test/test_attributes.rb
test/test_commands.rb
test/test_encoding.rb
test/test_extensions.rb
test/test_helper.rb

Added support for `--list-parse-options`, `--parse-option=OPTION`, `--list-render-options`, and `--render-option=OPTION` on the command line.
I always find I want to pass in `SOURCEPOS` and other options 😄

Add command line input for parse and render options

---

README.md

Comment is out of date as of 4397b956.  Use `puts` for Rubyishness.

clear up an example in the README

---

ext/commonmarker/commonmarker.c
test/test_tasklists.rb

This PR adds a method `Node#tasklist_item_checked=` to modify checkbox states of tasklist nodes by using cmark_gfm's API (`cmark_gfm_extensions_set_tasklist_item_checked`).

Add Node#tasklist_item_checked=

---

lib/commonmarker/node/inspect.rb

This PR fixes a warning like:
> Building YARD (yri) index for commonmarker-0.21.0...
> lib/commonmarker/node/inspect.rb:14: [UnknownParam] @param tag has unknown parameter name: pp

Avoid a YARD annotation warning

---

lib/commonmarker/renderer/html_renderer.rb

This mismatched indentation causes following warning message when running codes with `-w` flag.
```
/Users/naoty/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/commonmarker-0.21.0/lib/commonmarker/renderer/html_renderer.rb:73: warning: mismatched indentations at 'end' with 'else' at 71
```

Fix mismatched indentation

---

ext/commonmarker/commonmarker.c
test/test_renderer.rb

Fixes #130.
Looking at this code makes me feel weird. I guess we kind of leak `result` in these methods. They're allocated from the arena the node belongs to, so they get reset whenever `rb_markdown_to_html` is called, which should be often enough, but if people don't use that method, these might be leaky.

Copy encoding when escaping hrefs/HTML

---

.github/workflows/test.yml
.rubocop.yml
bin/commonmarker
commonmarker.gemspec
lib/commonmarker/config.rb
lib/commonmarker/node/inspect.rb
lib/commonmarker/renderer.rb
test/test_maliciousness.rb

Remove `ruby-enum` dependency

---

.gitignore
README.md
bin/commonmarker
ext/commonmarker/commonmarker.c
lib/commonmarker/config.rb
lib/commonmarker/node.rb
test/test_commands.rb
test/test_encoding.rb
test/test_xml.rb

`cmark-gfm` supports rending to the XML format and exports the correct functions.  So I've added support to the `Node` class so you can now do `doc.to_xml`.
Also added support for a new command line option, `—to=FORMAT` (which mirrors the option in `cmark-gfm`) that allows you to specify the output format.  Since `to_plaintext` and `to_commonmark` were already supported internally, possible output formats is `html`, `xml`, `plaintext`, and `CommonMark`. For example `commonmarker --to=xml`
Currently `man` and `latex` are not supported output formats.

Add support for rendering XML from cmark-gfm

---

README.md
lib/commonmarker/config.rb
test/test_basics.rb
test/test_extensions.rb
test/test_maliciousness.rb
test/test_smartpunct.rb

Hullo!
This PR "normalizes" the option bit mask flags that are made available as `parse` and `render` options respectively.
When you use `CommonMarker.render_html` we load up `:render` options, and when you use `CommonMarker.render_doc` we load up `:parse` options. 
This makes sense; some options are only available to the html renderer, and it doesn't make sense to pass them down to the parser.
However, both `render_html` and `render_doc` initialize the parser with the provided options masked integer. Assuming that I'm looking at the right code, both [`rb_parse_document`](https://github.com/gjtorikian/commonmarker/blob/580f0fdac2a41042de1bbe3497487dcbfc5e20fe/ext/commonmarker/commonmarker.c#L308) and [`rb_markdown_to_html`](https://github.com/gjtorikian/commonmarker/blob/580f0fdac2a41042de …

Normalize parse and render options

---

.github/workflows/test.yml

This PR uses the `bundler-cache` feature of the Ruby-maintained Action `ruby/setup-ruby`.
[See `ruby/setup-ruby` parameters declaration](https://github.com/ruby/setup-ruby/blob/master/action.yml) for more information.

CI: Drop duplicate bundle install

---

Gemfile
bin/commonmarker
commonmarker.gemspec
ext/commonmarker/commonmarker.c
lib/commonmarker.rb
test/benchmark.rb

With README.md from this repo:
1ee03a81dcc922a3c75245a83e2f85f2a8593fe3 Fix benchmark, switch it to `benchmark-ips` and add xml + `Node#to_html`
```
input size = 9206 bytes
Warming up --------------------------------------
redcarpet     1.998k i/100ms
commonmarker with to_html
652.000  i/100ms
commonmarker with to_xml
651.000  i/100ms
commonmarker with ruby HtmlRenderer
140.000  i/100ms
commonmarker with render_doc.to_html
1.021k i/100ms
kramdown    17.000  i/100ms
Calculating -------------------------------------
redcarpet     21.305k (± 1.5%) i/s -    107.892k in   5.065176s
commonmarker with to_html
6.127k (± 3.9%) i/s -     30.644k in   5.009868s
commonmarker with to_xml
5.775k (± 3.9%) i/s -     29.295k in   5.080767s
commonmarker with ruby HtmlRenderer
1.278k (± 6.1%) i/s - …
```

Fixup benchmark and speedup a little, fixes #141

---

ext/commonmarker/commonmarker.c

This PR makes updates to allow this gem to work properly with Ruby 3.2.
The addition of the `rb_undef_alloc_func` calls ensures that we undefine allocate for T_DATA classes. This relates to a change in Ruby introduced here: https://github.com/ruby/ruby/pull/4604 (opened from [this issue](https://bugs.ruby-lang.org/issues/18007)).

Add rb_undef_alloc_func for Node

---

.github/workflows/lint.yml
.github/workflows/test.yml
lib/commonmarker.rb
lib/commonmarker/config.rb
lib/commonmarker/renderer.rb
lib/commonmarker/version.rb
test/test_basics.rb
test/test_commands.rb
test/test_commonmark.rb
test/test_doc.rb
test/test_encoding.rb
test/test_extensions.rb
test/test_gc.rb
test/test_linebreaks.rb
test/test_maliciousness.rb
test/test_node.rb
test/test_pathological_inputs.rb
test/test_renderer.rb
test/test_smartpunct.rb
test/test_spec.rb
test/test_tasklists.rb

This is a PR to test the build and release of the old, tired and true C gem.
@phillmv the idea is that you and whomever will use `c-api-stable` as the base.

C API stable test

---

.github/workflows/test.yml
ext/commonmarker/src/comrak_options.rs
lib/commonmarker/config.rb
lib/commonmarker/version.rb
test/test_frontmatter.rb

Closes https://github.com/gjtorikian/commonmarker/issues/202

Frontmatter parse tweak

---

.cross_rubies
.github/workflows/cruby-build-and-install.yml
.github/workflows/generic-build-and-install.yml
.github/workflows/lint.yml
.github/workflows/tag_and_release.yml
.github/workflows/test.yml
Cargo.lock
commonmarker.gemspec
lib/commonmarker/version.rb
rakelib/extension.rake
script/test-gem-installation
test/test_extensions.rb
test/test_pathological_inputs.rb

Should close https://github.com/gjtorikian/commonmarker/issues/211

Provide 3.2 build support

---

commonmarker.gemspec
ext/commonmarker/extconf.rb
lib/commonmarker/version.rb

Per @ianks at https://github.com/gjtorikian/commonmarker/pull/212#issuecomment-1374866289, I try to avoid using Ruby's own Cargo builder here. Tested it myself with darwin-arm64 and linux-x86_64 on 3.1.2 and 3.2.0 as best I could, but CI might have more to say.

always use rb_sys (don't use Ruby's emerging cargo tooling where available)

---

README.md

- Fix the name of the extensions hash, from `extensions` to `extension`
- Fix `render_html` to `to_html`
- Remove redundant dot

Fix a couple of misleading README points

---

README.md

- Make its code sample, syntax highlighted
- Instead of using it as "an example of a plugin", use it in its own section, in preparation for future plugins in the future, and to save users the time to search for other plugins.
- Fix the name of the theme used in the example, it was wrong.
- Add a list of supported themes

Clarify syntax highlighter plugin usage in README

---

ext/commonmarker/arena.c
ext/commonmarker/autolink.c
ext/commonmarker/cmark-gfm-core-extensions.h
ext/commonmarker/cmark-gfm.h
ext/commonmarker/cmark.c
ext/commonmarker/html.c
ext/commonmarker/node.c
ext/commonmarker/node.h
ext/commonmarker/table.c
lib/commonmarker/version.rb
test/test_footnotes.rb

This PR updates cmark-upstream to `0.29.0.gfm.9`

Update cmark-upstream to `0.29.0.gfm.9`

---

lib/commonmarker/version.rb
test/fixtures/upstream/spec.txt
test/test_footnotes.rb
test/test_syntax_highlighting.rb

This PR changes a few of the output test HTML to account for new updates in comrak 0.17.

Updates from upstream

---

.gitignore
ext/commonmarker/src/options.rs
lib/commonmarker/config.rb
lib/commonmarker/version.rb
test/frontmatter_test.rb

fix #256
With the fix, restores expected behavior
```ruby
require 'commonmarker'
Commonmarker.to_html("---\nyaml: true\nage: 42\n---\n# Title 1", options: { extension: { front_matter_delimiter: '---' } } )
```
Note, the extension is still stripping anchors tho.
```ruby
Commonmarker.to_html("---\nyaml: true\nage: 42\n---\n# Title 1" )
```

fix front_matter_delimiter type

---

.vscode/settings.json
README.md
ext/commonmarker/src/lib.rs
ext/commonmarker/src/plugins/syntax_highlighting.rs
lib/commonmarker/version.rb
test/syntax_highlighting_test.rb

Closes https://github.com/gjtorikian/commonmarker/issues/258.

Classy highlighting

---

README.md
ext/commonmarker/src/options.rs
lib/commonmarker/config.rb
lib/commonmarker/version.rb
test/sourcepos_test.rb

This pull request fixes an issue introduced in `commonmarker` version 1.0.0, where the ability to specify the `sourcepos` option was unintentionally(?) removed. 
The goal is to restore the functionality of specifying `sourcepos`.

Add sourcepos option

---

.github/dependabot.yml
.github/workflows/test.yml
Cargo.lock
commonmarker.gemspec
ext/commonmarker/Cargo.toml
lib/commonmarker/version.rb

Closes https://github.com/gjtorikian/commonmarker/issues/281

Support ruby-head 

---

ext/commonmarker/src/node.rs
lib/commonmarker/version.rb
test/node_test.rb

Hiya! What do you think of this? Currently the `literal` members of Code and CodeBlock nodes isn't exposed anywhere.
The discrepancy between these and `text()`-fetchable things is a bit unfortunate on the Comrak side, but it's a side-effect of its legacy (i.e. the implication that `text()` means "get me the content of a Text node, and fail if it isn't one") — I see no reason to do the same to `string_content` just because of what it's backed by currently.
Fixes #289.

Expose code and code blocks' literals via string_content/=.

---

test/benchmark.rb

The benchmark test for `Commonmarker.parse` is hard-coded to the `large` input file. This change fixes the reference for the benchmark.

benchmark: correct Commonmarker::Node.to_html input.

---

README.md

The readme mentions that Node#each will iterate on a node and its first-level children (implying self will be yielded), but from [the source file](https://github.com/gjtorikian/commonmarker/blob/55c3b03708b31f1af37a53b3312f91400594223d/lib/commonmarker/node.rb#L27) it seems that only the children are yielded.
Some basic testing seems to yield just the children for me, but feel free to correct me if I'm missing something here :)

Readme defintion of `each` seems ot conflict with implementation

---

ext/commonmarker/commonmarker.c
lib/commonmarker/version.rb

In a few places we were passing malloc'd memory to rb_str_new (and variants) and returning the resulting VALUE without freeing the passed C string buffer.
One of these leaks was introduced by https://github.com/gjtorikian/commonmarker/pull/171 (we can see that some calls to `free` were lost in the rewrite), but others seem to predate that.
After this change I'm able to run `ASAN_OPTIONS="detect_leaks=1" RUBY_FREE_AT_EXIT=1 bundle exec rake` with an ASAN-built Ruby without errors.
``` ruby
require "commonmarker"
10.times do
100.times do
CommonMarker.render_html("hello, world\n"*10000)
end
puts `ps -orss= -p #$$`
end
```
```
❯ bundle exec ruby test.rb
74736
112112
112112
128496
172016
203120
203120
203120
241392
266480
```
cc @anticomputer @phillmv

[0.x] Fix memory leaks of string buffers

---

README.md
ext/commonmarker/src/options.rs
lib/commonmarker/config.rb
test/tasklists_test.rb

Fixes #364.
By enabling the `tasklist_classes` in render_options you can easily style the HTML generated by the tasklist extension.

Adds tasklist_classes to the list of render options.

---

README.md

Fixes #381
Fixes a typo in the wikilinks_title_after_pipe description.

fix: correct typo in wikilinks_title_after_pipe description
